apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scalable-pod-identifier-hpa
spec:
  minReplicas: 1
  maxReplicas: 10

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaletestapp

  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
